### ISSUE TITLE
Invalid header error on firehose_indexer.dart

### ISSUE THREAD

**Issue by azigler** [skyfeed-dev/indexer#1] opened 2023-07-04 23:31 UTC
I'm running this on a small Droplet right now that I use for a few things.

2 GB Memory
25 GB Disk + 30 GB mounted
Ubuntu 22.04 (LTS) x64

After running `dart run bin/firehose_indexer.dart` for a few minutes, I keep getting this error. I checked my usage charts and I don't seem to be hitting limits on CPU, memory, or disk space.

Any thoughts @redsolver about what I might need to try? I was able to crawl around in SurrealDB and confirm that data is flowing in when it is working.

```dart
Unhandled exception:
INVALID HEADER {t: #tombstone, op: 1}
#0      processMessage (file:///mnt/barn_1/indexer/bin/firehose_indexer.dart:61:7)
#1      main.<anonymous closure> (file:///mnt/barn_1/indexer/bin/firehose_indexer.dart:43:7)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#5      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#6      _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
#7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#12     _StreamController._add (dart:async/stream_controller.dart:650:7)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#17     _StreamController._add (dart:async/stream_controller.dart:650:7)
#18     _StreamController.add (dart:async/stream_controller.dart:598:5)
#19     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:335:23)
#26     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#32     _StreamController._add (dart:async/stream_controller.dart:650:7)
#33     _StreamController.add (dart:async/stream_controller.dart:598:5)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#39     _StreamController._add (dart:async/stream_controller.dart:650:7)
#40     _StreamController.add (dart:async/stream_controller.dart:598:5)
#41     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1114:19)
#42     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#44     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#45     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by azigler** [comment] 2023-07-04 23:43
Further testing:

I ran `dart run bin/historical_indexer.dart` and the process ended up taking all the CPU and locking. After cancelling and trying the `firehose_indexer` again, I now get this error every every time. It either fails instantly or grabs a message where I get this error before the process fails:

```dart
[E]  RPC request failed: {error: {code: -32000, message: There was a problem with the database: Found '2023-07-04T23:21:21.431761' for field `createdAt`, with record `post:plc_jbnriginiqitcc4h5cngn3qy_3jzqa7chqqe2e`, but expected a datetime}, id: 1474} (update [post:plc_jbnriginiqitcc4h5cngn3qy_3jzqa7chqqe2e, {author: did:plc_jbnriginiqitcc4h5cngn3qy, text: Happy Independence Day: Fourth of July Celebrations in the Nation’s Capital
```

**Comment by redsolver** [comment] 2023-07-05 14:43
Thanks for reporting, it's a bug, I just pushed a fix

**Closed as completed by redsolver** 2023-07-05 14:43 UTC

**Comment by redsolver** [comment] 2023-07-05 14:47
Oh and the second error is likely caused by a different timezone, I just pushed a fix for that too

**Comment by azigler** [comment] 2023-07-05 19:08
@redsolver You rock! I will spin these back up today and report back. 🚀

**Comment by azigler** [comment] 2023-07-05 22:56
@redsolver Circling back to report that this fixed the issue for both the firehose and the historical indexers! 🙌 Nice work.

Separately, re: the historical indexer, I find that I run out of memory eventually and the process is killed. Do you have a recommended RAM suggestion to run this script on? Separately, if it fails/is stopped/is killed and then you restart it, does it know where it left off and continue from there or does it start over from the top? If it keeps a cursor and continues it's place, then I could try running it a few times to get the final historical record, but I wanted to ask first before going that route or allotting more RAM.

**Comment by redsolver** [comment] 2023-07-06 10:09
oh yeah last time I used the historical indexer there were only 70k accounts, now there are a lot more. iirc it does not remember where it stopped, could you please create a new issue for that feature?
